apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: higher-or-lower
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlexSitu01/vps-0-infra2.git
    targetRevision: HEAD
    path: services/higherOrLower
  destination:
    server: https://kubernetes.default.svc
    namespace: higher-or-lower
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true