apiVersion: apps/v1
kind: Deployment
metadata:
  name: higher-or-lower
  labels:
    app: higher-or-lower
spec:
  selector:
    matchLabels:
      app: higher-or-lower
  template:
    metadata:
      labels:
        app: higher-or-lower
    spec:
      containers:
        - name: higher-or-lower
          image: alexsitu1/hol:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: higher-or-lower
spec:
  selector:
    app: higher-or-lower
  ports:
    - port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: higher-or-lower
spec:
  parentRefs:
    - name: main-gateway
      namespace: kube-system
      sectionName: https
      kind: Gateway

  hostnames:
    - games.alexsitu.cc

  rules:
    - backendRefs:
        - name: higher-or-lower
          port: 3000